--  --
CREATE OR REPLACE FORCE VIEW "PAOZ"."V_LEADEREMP" ("UNICOD", "UNICOD2", "IDNO", "EMPNO", "NAME", "TITCOD", "TITLE", "DB", "PKIND") AS 
SELECT UNICOD,UNICOD,IDNO,EMPNO,NAME,ROLID,ROLNAME,'3','1' FROM V_LEADER
UNION
SELECT UNICOD,UNICOD2,IDNO,EMPNO,NAME,TITCOD,TITLE,'3',PKIND FROM V_EMPLOYEE
WHERE IDNO IN ('E220507472','H101632184') --蔡璦琪,鄭紹宇
UNION
SELECT UNICOD,UNICOD2,IDNO,EMPNO,NAME,TITCOD,TITLE,'5',PKIND FROM V_EMPLOYEE
WHERE (PKIND <> '3')
AND   ((TITLE <> '組長') and (TITLE <> '主任') and (TITLE <> '主計主任') and (TITLE <> '校長'));
 

-- V_LEADER , V_LEADEREMP --

